// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (created_at, updated_at, email)
VALUES (
    NOW(), NOW(), $1
)
RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
